repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: ^butler_bot/|^billing/|^common/|^migrations/
        args: [
            "--max-line-length=100",
            "--exclude=*migrations*",
        ]

  - repo: local
    hooks:
      - id: yapf
        name: Main linter
        entry: python -m yapf
        args: [ '--parallel', '--recursive', '--diff']
        language: system
        types: [ python ]


#  - repo: https://github.com/PyCQA/pylint
#    rev: pylint-2.6.0
#    hooks:
#      - id: pylint
